package inchi;
import java.nio.ByteBuffer;

import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.Pointer;
/**
 * JNA Wrapper for library <b>inchi</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class InchiLibrary implements Library {
  public static final String JNA_LIBRARY_NAME = "inchi";
  public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(InchiLibrary.JNA_LIBRARY_NAME);
  static {
    Native.register(InchiLibrary.class, InchiLibrary.JNA_NATIVE_LIB);
  }
  /** enum values */
  public static interface tagINCHIRadical {
    /** <i>native declaration : line 59</i> */
    public static final int INCHI_RADICAL_NONE = 0;
    /** <i>native declaration : line 60</i> */
    public static final int INCHI_RADICAL_SINGLET = 1;
    /** <i>native declaration : line 61</i> */
    public static final int INCHI_RADICAL_DOUBLET = 2;
    /** <i>native declaration : line 62</i> */
    public static final int INCHI_RADICAL_TRIPLET = 3;
  };
  /** enum values */
  public static interface tagINCHIBondType {
    /** <i>native declaration : line 67</i> */
    public static final int INCHI_BOND_TYPE_NONE = 0;
    /** <i>native declaration : line 68</i> */
    public static final int INCHI_BOND_TYPE_SINGLE = 1;
    /** <i>native declaration : line 69</i> */
    public static final int INCHI_BOND_TYPE_DOUBLE = 2;
    /** <i>native declaration : line 70</i> */
    public static final int INCHI_BOND_TYPE_TRIPLE = 3;
    /**
     * avoid by all means<br>
     * <i>native declaration : line 71</i>
     */
    public static final int INCHI_BOND_TYPE_ALTERN = 4;
  };
  /** enum values */
  public static interface tagINCHIBondStereo2D {
    /** <i>native declaration : line 75</i> */
    public static final int INCHI_BOND_STEREO_NONE = 0;
    /** <i>native declaration : line 76</i> */
    public static final int INCHI_BOND_STEREO_SINGLE_1UP = 1;
    /** <i>native declaration : line 77</i> */
    public static final int INCHI_BOND_STEREO_SINGLE_1EITHER = 4;
    /** <i>native declaration : line 78</i> */
    public static final int INCHI_BOND_STEREO_SINGLE_1DOWN = 6;
    /** <i>native declaration : line 80</i> */
    public static final int INCHI_BOND_STEREO_SINGLE_2UP = -1;
    /** <i>native declaration : line 81</i> */
    public static final int INCHI_BOND_STEREO_SINGLE_2EITHER = -4;
    /** <i>native declaration : line 82</i> */
    public static final int INCHI_BOND_STEREO_SINGLE_2DOWN = -6;
    /**
     * unknown stereobond geometry<br>
     * <i>native declaration : line 84</i>
     */
    public static final int INCHI_BOND_STEREO_DOUBLE_EITHER = 3;
  };
  /** enum values */
  public static interface tagINCHIStereoType0D {
    /** <i>native declaration : line 407</i> */
    public static final int INCHI_StereoType_None = 0;
    /** <i>native declaration : line 408</i> */
    public static final int INCHI_StereoType_DoubleBond = 1;
    /** <i>native declaration : line 409</i> */
    public static final int INCHI_StereoType_Tetrahedral = 2;
    /** <i>native declaration : line 410</i> */
    public static final int INCHI_StereoType_Allene = 3;
  };
  /** enum values */
  public static interface tagINCHIStereoParity0D {
    /** <i>native declaration : line 415</i> */
    public static final int INCHI_PARITY_NONE = 0;
    /**
     * 'o'<br>
     * <i>native declaration : line 416</i>
     */
    public static final int INCHI_PARITY_ODD = 1;
    /**
     * 'e'<br>
     * <i>native declaration : line 417</i>
     */
    public static final int INCHI_PARITY_EVEN = 2;
    /**
     * 'u'<br>
     * <i>native declaration : line 418</i>
     */
    public static final int INCHI_PARITY_UNKNOWN = 3;
    /**
     * '?' -- should not be used; however, see Note above<br>
     * <i>native declaration : line 420</i>
     */
    public static final int INCHI_PARITY_UNDEFINED = 4;
  };
  /** enum values */
  public static interface tagRetValGetINCHI {
    /** <i>native declaration : line 727</i> */
    public static final int inchi_Ret_BREAK = -100;
    /**
     * not used in InChI library<br>
     * <i>native declaration : line 728</i>
     */
    public static final int inchi_Ret_SKIP = -2;
    /**
     * no structural data has been provided<br>
     * <i>native declaration : line 729</i>
     */
    public static final int inchi_Ret_EOF = -1;
    /**
     * Success; no errors or warnings<br>
     * <i>native declaration : line 730</i>
     */
    public static final int inchi_Ret_OKAY = 0;
    /**
     * Success; warning(s) issued<br>
     * <i>native declaration : line 731</i>
     */
    public static final int inchi_Ret_WARNING = 1;
    /**
     * Error: no InChI has been created<br>
     * <i>native declaration : line 732</i>
     */
    public static final int inchi_Ret_ERROR = 2;
    /**
     * Severe error: no InChI has been created (typically, memory allocation failure)<br>
     * <i>native declaration : line 733</i>
     */
    public static final int inchi_Ret_FATAL = 3;
    /**
     * Unknown program error<br>
     * <i>native declaration : line 734</i>
     */
    public static final int inchi_Ret_UNKNOWN = 4;
    /**
     * Previuos call to InChI has not returned yet<br>
     * <i>native declaration : line 735</i>
     */
    public static final int inchi_Ret_BUSY = 5;
  };
  /** enum values */
  public static interface tagRetValMOL2INCHI {
    /**
     * Success; no errors or warnings<br>
     * <i>native declaration : line 743</i>
     */
    public static final int mol2inchi_Ret_OKAY = 0;
    /**
     * Success; warning(s) issued<br>
     * <i>native declaration : line 744</i>
     */
    public static final int mol2inchi_Ret_WARNING = 1;
    /**
     * generic Error: no InChI has been created<br>
     * <i>native declaration : line 745</i>
     */
    public static final int mol2inchi_Ret_ERROR = 2;
    /**
     * get structure Error: no InChI has been created<br>
     * <i>native declaration : line 746</i>
     */
    public static final int mol2inchi_Ret_ERROR_get = 4;
    /**
     * compute InChI Error: no InChI has been created<br>
     * <i>native declaration : line 747</i>
     */
    public static final int mol2inchi_Ret_ERROR_comp = 5;
  };
  /** enum values */
  public static interface tagRetValCheckINCHI {
    /** <i>native declaration : line 755</i> */
    public static final int INCHI_VALID_STANDARD = 0;
    /** <i>native declaration : line 756</i> */
    public static final int INCHI_VALID_NON_STANDARD = 1;
    /** <i>native declaration : line 757</i> */
    public static final int INCHI_VALID_BETA = 2;
    /** <i>native declaration : line 758</i> */
    public static final int INCHI_INVALID_PREFIX = 3;
    /** <i>native declaration : line 759</i> */
    public static final int INCHI_INVALID_VERSION = 4;
    /** <i>native declaration : line 760</i> */
    public static final int INCHI_INVALID_LAYOUT = 5;
    /** <i>native declaration : line 761</i> */
    public static final int INCHI_FAIL_I2I = 6;
  };
  /** enum values */
  public static interface tagRetValGetINCHIKey {
    /** <i>native declaration : line 1062</i> */
    public static final int INCHIKEY_VALID_STANDARD = 0;
    /** <i>native declaration : line 1063</i> */
    public static final int INCHIKEY_VALID_NON_STANDARD = -1;
    /** <i>native declaration : line 1064</i> */
    public static final int INCHIKEY_INVALID_LENGTH = 1;
    /** <i>native declaration : line 1065</i> */
    public static final int INCHIKEY_INVALID_LAYOUT = 2;
    /** <i>native declaration : line 1066</i> */
    public static final int INCHIKEY_INVALID_VERSION = 3;
  };
  public static final int FIND_RING_SYSTEMS = (int)1;
  public static final int FIND_RINS_SYSTEMS_DISTANCES = (int)0;
  public static final int FIX_DOCANON_RETCODE_RESET_BUG = (int)1;
  public static final int MAXVAL = (int)20;
  public static final int ATOM_EL_LEN = (int)6;
  public static final int NUM_H_ISOTOPES = (int)3;
  public static final int ISOTOPIC_SHIFT_FLAG = (int)10000;
  public static final int ISOTOPIC_SHIFT_MAX = (int)100;
  public static final int NO_ATOM = (int)(-1);
  public static final String INCHI_STRING_PREFIX = (String)"InChI=";
  public static final int LEN_INCHI_STRING_PREFIX = (int)6;
  public static final int STR_ERR_LEN = (int)256;
  public static final int INCHIKEY_OK = (int)0;
  public static final int INCHIKEY_UNKNOWN_ERROR = (int)1;
  public static final int INCHIKEY_EMPTY_INPUT = (int)2;
  public static final int INCHIKEY_INVALID_INCHI_PREFIX = (int)3;
  public static final int INCHIKEY_NOT_ENOUGH_MEMORY = (int)4;
  public static final int INCHIKEY_INVALID_INCHI = (int)20;
  public static final int INCHIKEY_INVALID_STD_INCHI = (int)21;
  public static final int MAX_NUM_STEREO_ATOM_NEIGH = (int)4;
  public static final int MAX_NUM_STEREO_BONDS = (int)3;
  public static final int INCHI_NUM = (int)2;
  /**
   * Original signature : <code>void FreeInChIExtInput(inchi_Input_Polymer*, inchi_Input_V3000*)</code><br>
   * <i>native declaration : line 681</i>
   */
  //public static native void FreeInChIExtInput(inchi_Input_Polymer polymer, inchi_Input_V3000 v3000);
  /**
   * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br>
   * GetINCHI / GetStdINCHI<br>
   * inchi_Input is created by the user; strings in inchi_Output are allocated and deallocated by InChI<br>
   * inchi_Output does not need to be initilized out to zeroes; see FreeNCHI()/FreeSTDINCHI() on how to deallocate it<br>
   * Valid options for GetINCHI:<br>
   * (use - instead of / for O.S. other than MS Windows)<br>
   * Structure perception (compatible with stdInChI)<br>
   * /NEWPSOFF   /DoNotAddH   /SNon<br>
   * Stereo interpretation (lead to generation of non-standard InChI)<br>
   * /SRel /SRac /SUCF /ChiralFlagON /ChiralFlagOFF<br>
   * InChI creation options (lead to generation of non-standard InChI)<br>
   * /SUU /SLUUD   /FixedH  /RecMet  /KET /15T<br>
   * GetINCHI produces standard InChI if no InChI creation/stereo modification options<br>
   * are specified. Inveresely, if any of SUU/SLUUD/RecMet/FixedH/Ket/15T/SRel/SRac/SUCF<br>
   * options are specified, generated InChI will be non-standard one.<br>
   * GetStdINCHI produces standard InChI only.<br>
   * The valid structure perception options are:<br>
   * /NEWPSOFF   /DoNotAddH   /SNon<br>
   * Other options are:<br>
   * /AuxNone    Omit auxiliary information (default: Include)<br>
   * /Wnumber    Set time-out per structure in seconds; W0 means unlimited<br>
   * In InChI library the default value is unlimited<br>
   * /OutputSDF  Output SDfile instead of InChI<br>
   * /WarnOnEmptyStructure<br>
   * Warn and produce empty InChI for empty structure<br>
   * /SaveOpt    Save custom InChI creation options (non-standard InChI)<br>
   * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br>
   * Original signature : <code>int GetINCHI(inchi_Input*, inchi_Output*)</code><br>
   * <i>native declaration : line 835</i>
   */
  public static native int GetINCHI(tagINCHI_Input inp, tagINCHI_Output out);
  /**
   * Original signature : <code>int GetStdINCHI(inchi_Input*, inchi_Output*)</code><br>
   * <i>native declaration : line 836</i>
   */
  public static native int GetStdINCHI(tagINCHI_Input inp, tagINCHI_Output out);
  /**
   * Extended version of GetINCHI supporting v. 1.05 extensions: V3000; polymers<br>
   * Original signature : <code>int GetINCHIEx(inchi_InputEx*, inchi_Output*)</code><br>
   * <i>native declaration : line 840</i>
   */
  public static native int GetINCHIEx(inchi_InputEx inp, tagINCHI_Output out);
  /**
   * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br>
   * FreeINCHI / FreeStdINCHI<br>
   * should be called to deallocate char* pointers<br>
   * obtained from each GetINCHI /GetStdINCHI call<br>
   * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br>
   * Original signature : <code>void FreeINCHI(inchi_Output*)</code><br>
   * <i>native declaration : line 850</i>
   */
  public static native void FreeINCHI(tagINCHI_Output out);
  /**
   * Original signature : <code>void FreeStdINCHI(inchi_Output*)</code><br>
   * <i>native declaration : line 851</i>
   */
  public static native void FreeStdINCHI(tagINCHI_Output out);
  /**
   * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br>
   * GetStructFromINCHI / GetStructFromStdINCHI / GetStructFromINCHIEx<br>
   * inchi_Inputinchi_InputINCHI is created by the user; pointers in inchi_OutputStruct are allocated and deallocated by InChI<br>
   * inchi_OutputStruct does not need to be initialized out to zeroes; see FreeStructFromStdINCHI() on how to deallocate it<br>
   * Option /Inchi2Struct is not needed for GetStructFromINCHI()/GetStructFromStdINCHI()<br>
   * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br>
   * Original signature : <code>int GetStructFromINCHI(inchi_InputINCHI*, inchi_OutputStruct*)</code><br>
   * <i>native declaration : line 872</i>
   */
  public static native int GetStructFromINCHI(tagINCHI_InputINCHI inpInChI, tagINCHI_OutputStruct outStruct);
  /**
   * Original signature : <code>int GetStructFromStdINCHI(inchi_InputINCHI*, inchi_OutputStruct*)</code><br>
   * <i>native declaration : line 873</i>
   */
  public static native int GetStructFromStdINCHI(tagINCHI_InputINCHI inpInChI, tagINCHI_OutputStruct outStruct);
  /**
   * Original signature : <code>int GetStructFromINCHIEx(inchi_InputINCHI*, inchi_OutputStructEx*)</code><br>
   * <i>native declaration : line 874</i>
   */
  public static native int GetStructFromINCHIEx(tagINCHI_InputINCHI inpInChI, tagINCHI_OutputStructEx outStruct);
  /**
   * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br>
   * FreeStructFromINCHI / FreeStructFromStdINCHI / FreeStructFromINCHIEx<br>
   * should be called to deallocate pointers obtained from each<br>
   * GetStructFromStdINCHI / GetStructFromINCHI / GetStructFromINCHIEx<br>
   * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br>
   * Original signature : <code>void FreeStructFromINCHI(inchi_OutputStruct*)</code><br>
   * <i>native declaration : line 884</i>
   */
  public static native void FreeStructFromINCHI(tagINCHI_OutputStruct out);
  /**
   * Original signature : <code>void FreeStructFromStdINCHI(inchi_OutputStruct*)</code><br>
   * <i>native declaration : line 885</i>
   */
  public static native void FreeStructFromStdINCHI(tagINCHI_OutputStruct out);
  /**
   * Original signature : <code>void FreeStructFromINCHIEx(inchi_OutputStructEx*)</code><br>
   * <i>native declaration : line 886</i>
   */
  public static native void FreeStructFromINCHIEx(tagINCHI_OutputStructEx out);
  /**
   * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br>
   * GetINCHIfromINCHI<br>
   * GetINCHIfromINCHI does same as -InChI2InChI option: converts InChI into InChI for validation purposes<br>
   * It may also be used to filter out specific layers. For instance, /Snon would remove stereochemical layer<br>
   * Omitting /FixedH and/or /RecMet would remove Fixed-H or Reconnected layers<br>
   * To keep all InChI layers use options string "/FixedH /RecMet"; option /InChI2InChI is not needed<br>
   * inchi_InputINCHI is created by the user; strings in inchi_Output are allocated and deallocated by InChI<br>
   * inchi_Output does not need to be initilized out to zeroes; see FreeINCHI() on how to deallocate it<br>
   * Note: there is no explicit tool to conversion from/to standard InChI<br>
   * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br>
   * Original signature : <code>int GetINCHIfromINCHI(inchi_InputINCHI*, inchi_Output*)</code><br>
   * <i>native declaration : line 902</i>
   */
  public static native int GetINCHIfromINCHI(tagINCHI_InputINCHI inpInChI, tagINCHI_Output out);
  /**
   * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br>
   * Get_inchi_Input_FromAuxInfo / Get_std_inchi_Input_FromAuxInfo<br>
   * Input:<br>
   * szInchiAuxInfo: contains ASCIIZ string of InChI output for a single<br>
   * structure or only the AuxInfo line<br>
   * bDoNotAddH:    if 0 then InChI will be allowed to add implicit H<br>
   * bDiffUnkUndfStereo<br>
   * if not 0, use different labels for unknown and undefined stereo<br>
   * pInchiInp:     should have a valid pointer pInchiInp->pInp to an empty<br>
   * (all members = 0) inchi_Input structure<br>
   * Output:<br>
   * pInchiInp:     The following members of pInp may be filled during the call:<br>
   * atom, num_atoms, stereo0D, num_stereo0D<br>
   * Return value:  see RetValGetINCHI<br>
   * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br>
   * Original signature : <code>int Get_inchi_Input_FromAuxInfo(char*, int, int, InchiInpData*)</code><br>
   * <i>native declaration : line 956</i>
   */
  public static native int Get_inchi_Input_FromAuxInfo(ByteBuffer szInchiAuxInfo, int bDoNotAddH, int bDiffUnkUndfStereo, tagInchiInpData pInchiInp);
  /**
   * Original signature : <code>int Get_std_inchi_Input_FromAuxInfo(char*, int, InchiInpData*)</code><br>
   * <i>native declaration : line 961</i>
   */
  public static native int Get_std_inchi_Input_FromAuxInfo(ByteBuffer szInchiAuxInfo, int bDoNotAddH, tagInchiInpData pInchiInp);
  /**
   * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br>
   * Free_inchi_Input / Free_std_inchi_Input<br>
   * To deallocate and write zeroes into the changed members of pInchiInp->pInp call<br>
   * Free_inchi_Input( inchi_Input *pInp )<br>
   * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br>
   * Original signature : <code>void Free_inchi_Input(inchi_Input*)</code><br>
   * <i>native declaration : line 974</i>
   */
  public static native void Free_inchi_Input(tagINCHI_Input pInp);
  /**
   * Original signature : <code>void Free_std_inchi_Input(inchi_Input*)</code><br>
   * <i>native declaration : line 975</i>
   */
  public static native void Free_std_inchi_Input(tagINCHI_Input pInp);
  /**
   * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br>
   * CheckINCHI<br>
   * Check if the string represents valid InChI/standard <br>
   * Input:<br>
   * szINCHI     source InChI<br>
   * strict      if 0, just briefly check for proper layout (prefix, version, etc.)<br>
   * The result may not be strict.<br>
   * If not 0, try to perform InChI2InChI conversion and<br>
   * returns success if a resulting InChI string exactly match source.<br>
   * The result may be 'false alarm' due to imperfectness of conversion.<br>
   * Returns:<br>
   * success/errors codes<br>
   * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br>
   * Original signature : <code>int CheckINCHI(const char*, const int)</code><br>
   * <i>native declaration : line 994</i>
   */
  public static native int CheckINCHI(String szINCHI, int strict);
  /**
   * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br>
   * GetINCHIKeyFromINCHI<br>
   * Calculate InChIKey by InChI string.<br>
   * Input:<br>
   * szINCHISource<br>
   * source InChI string<br>
   * xtra1<br>
   * =1 calculate hash extension (up to 256 bits; 1st block)<br>
   * xtra2<br>
   * =1 calculate hash extension (up to 256 bits; 2nd block)<br>
   * Output:<br>
   * szINCHIKey<br>
   * InChIKey string<br>
   * The user-supplied buffer szINCHIKey should be at least 28 bytes long.<br>
   * szXtra1<br>
   * hash extension (up to 256 bits; 1st block) string<br>
   * Caller should allocate space for 64 characters + trailing NULL<br>
   * szXtra2<br>
   * hash extension (up to 256 bits; 2nd block) string<br>
   * Caller should allocate space for 64 characters + trailing NULL<br>
   * Returns:<br>
   * success/errors codes<br>
   * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br>
   * Original signature : <code>int GetINCHIKeyFromINCHI(const char*, const int, const int, char*, char*, char*)</code><br>
   * <i>native declaration : line 1113</i>
   */
  public static native int GetINCHIKeyFromINCHI(String szINCHISource, int xtra1, int xtra2, byte[] szINCHIKey, byte[] szXtra1, byte[] szXtra2);
  /**
   * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br>
   * GetStdINCHIKeyFromStdINCHI<br>
   * "Standard" counterpart<br>
   * For compatibility with v. 1.02std, no extra hash calculation is allowed.<br>
   * To calculate extra hash(es), use GetINCHIKeyFromINCHI with stdInChI as input.<br>
   * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br>
   * Original signature : <code>int GetStdINCHIKeyFromStdINCHI(const char*, char*)</code><br>
   * <i>native declaration : line 1131</i>
   */
  public static native int GetStdINCHIKeyFromStdINCHI(String szINCHISource, ByteBuffer szINCHIKey);
  /**
   * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br>
   * CheckINCHIKey<br>
   * Check if the string represents valid InChIKey.<br>
   * Input:<br>
   * szINCHIKey<br>
   * source InChIKey string<br>
   * Returns:<br>
   * success/errors codes<br>
   * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br>
   * Original signature : <code>int CheckINCHIKey(const char*)</code><br>
   * <i>native declaration : line 1146</i>
   */
  public static native int CheckINCHIKey(String szINCHIKey);
  /**
   * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br>
   * INCHIGEN_Create / STDINCHIGEN_Create<br>
   * InChI Generator: create generator<br>
   * Returns handle of generator object or NULL on failure<br>
   * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br>
   * Original signature : <code>INCHIGEN_HANDLE INCHIGEN_Create()</code><br>
   * <i>native declaration : line 1312</i>
   */
  public static native Pointer INCHIGEN_Create();
  /**
   * Original signature : <code>INCHIGEN_HANDLE STDINCHIGEN_Create()</code><br>
   * <i>native declaration : line 1314</i>
   */
  public static native Pointer STDINCHIGEN_Create();
  /**
   * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br>
   * INCHIGEN_Setup / STDINCHIGEN_Setup<br>
   * InChI Generator: setup<br>
   * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br>
   * Original signature : <code>int INCHIGEN_Setup(INCHIGEN_HANDLE, INCHIGEN_DATA*, inchi_Input*)</code><br>
   * <i>native declaration : line 1324</i>
   */
  public static native int INCHIGEN_Setup(Pointer HGen, tagINCHIGEN_DATA pGenData, tagINCHI_Input pInp);
  /**
   * Original signature : <code>int STDINCHIGEN_Setup(INCHIGEN_HANDLE, INCHIGEN_DATA*, inchi_Input*)</code><br>
   * <i>native declaration : line 1327</i>
   */
  public static native int STDINCHIGEN_Setup(Pointer HGen, tagINCHIGEN_DATA pGenData, tagINCHI_Input pInp);
  /**
   * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br>
   * INCHIGEN_DoNormalization / STDINCHIGEN_DoNormalization<br>
   * InChI Generator: structure normalization stage<br>
   * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br>
   * Original signature : <code>int INCHIGEN_DoNormalization(INCHIGEN_HANDLE, INCHIGEN_DATA*)</code><br>
   * <i>native declaration : line 1339</i>
   */
  public static native int INCHIGEN_DoNormalization(Pointer HGen, tagINCHIGEN_DATA pGenData);
  /**
   * Original signature : <code>int STDINCHIGEN_DoNormalization(INCHIGEN_HANDLE, INCHIGEN_DATA*)</code><br>
   * <i>native declaration : line 1341</i>
   */
  public static native int STDINCHIGEN_DoNormalization(Pointer HGen, tagINCHIGEN_DATA pGenData);
  /**
   * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br>
   * INCHIGEN_DoCanonicalization / STDINCHIGEN_DoCanonicalization<br>
   * InChI Generator: structure canonicalization stage<br>
   * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br>
   * Original signature : <code>int INCHIGEN_DoCanonicalization(INCHIGEN_HANDLE, INCHIGEN_DATA*)</code><br>
   * <i>native declaration : line 1352</i>
   */
  public static native int INCHIGEN_DoCanonicalization(Pointer HGen, tagINCHIGEN_DATA pGenData);
  /**
   * Original signature : <code>int STDINCHIGEN_DoCanonicalization(INCHIGEN_HANDLE, INCHIGEN_DATA*)</code><br>
   * <i>native declaration : line 1354</i>
   */
  public static native int STDINCHIGEN_DoCanonicalization(Pointer HGen, tagINCHIGEN_DATA pGenData);
  /**
   * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br>
   * INCHIGEN_DoSerialization / STDINCHIGEN_DoSerialization<br>
   * InChI Generator: InChI serialization stage<br>
   * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br>
   * Original signature : <code>int INCHIGEN_DoSerialization(INCHIGEN_HANDLE, INCHIGEN_DATA*, inchi_Output*)</code><br>
   * <i>native declaration : line 1365</i>
   */
  public static native int INCHIGEN_DoSerialization(Pointer HGen, tagINCHIGEN_DATA pGenData, tagINCHI_Output pResults);
  /**
   * Original signature : <code>int STDINCHIGEN_DoSerialization(INCHIGEN_HANDLE, INCHIGEN_DATA*, inchi_Output*)</code><br>
   * <i>native declaration : line 1368</i>
   */
  public static native int STDINCHIGEN_DoSerialization(Pointer HGen, tagINCHIGEN_DATA pGenData, tagINCHI_Output pResults);
  /**
   * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br>
   * INCHIGEN_Reset / STDINCHIGEN_Reset<br>
   * InChI Generator: reset stage (use before get next structure)<br>
   * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br>
   * Original signature : <code>void INCHIGEN_Reset(INCHIGEN_HANDLE, INCHIGEN_DATA*, inchi_Output*)</code><br>
   * <i>native declaration : line 1381</i>
   */
  public static native void INCHIGEN_Reset(Pointer HGen, tagINCHIGEN_DATA pGenData, tagINCHI_Output pResults);
  /**
   * Original signature : <code>void STDINCHIGEN_Reset(INCHIGEN_HANDLE, INCHIGEN_DATA*, inchi_Output*)</code><br>
   * <i>native declaration : line 1385</i>
   */
  public static native void STDINCHIGEN_Reset(Pointer HGen, tagINCHIGEN_DATA pGenData, tagINCHI_Output pResults);
  /**
   * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br>
   * INCHIGEN_Destroy / STDINCHIGEN_Destroy<br>
   * InChI Generator: destroy generator<br>
   * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br>
   * Original signature : <code>void INCHIGEN_Destroy(INCHIGEN_HANDLE)</code><br>
   * <i>native declaration : line 1397</i>
   */
  public static native void INCHIGEN_Destroy(Pointer HGen);
  /**
   * Original signature : <code>void STDINCHIGEN_Destroy(INCHIGEN_HANDLE)</code><br>
   * <i>native declaration : line 1398</i>
   */
  public static native void STDINCHIGEN_Destroy(Pointer HGen);
  /**
   * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br>
   * MakeINCHIFromMolfileText<br>
   * Direct generation of InChI from Molfile supplied as text<br>
   * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br>
   * Original signature : <code>int MakeINCHIFromMolfileText(const char*, char*, inchi_Output*)</code><br>
   * <i>native declaration : line 1410</i>
   */
  public static native int MakeINCHIFromMolfileText(String moltext, String options, tagINCHI_Output result);
  public static void foo() {
    // TODO Auto-generated method stub
    
  }
}
